[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://boring-jones-8c602b.netlify.com/"
  to = "https://boring-jones-8c602b.netlify.com/docs/"
  force = true