---
title: "Customised Boxes (Alerts)"

lastmod: 2019-03-06T00:00:00.000Z

draft: false
type: docs
maths: true	

output:
  blogdown::html_page:
    toc: true

linktitle: "Customised Boxes (Alerts)"
menu:
  docs:
    parent: Website Management
    weight: 60

---

**Sun 21 July 2019 - Nick**

I've made a major change to the website so as to make it a little bit more attractive. 

The change involves allowing us to now put a customised box around various sections, such as the required readings, the summary at the beginning of a lesson, the list of concepts, an exercise, or a set of practice exercises or exam questions.

There are eight different types I've created, and the main distinction between them (except 'box' which also has a smaller h1 font) is that they have different icons in the top lefft corner of the box.

# How to use.
These boxes are tables, which use css styles to format the cells of the table.

This is an example of the code to create two sequential boxes

```
<table class="alert-readings"> <tbody> <tr>  <td>
# Readings
</td>  </tr>  <tr>  <td>
[insert readings here]
</td>  </tr> </tbody> </table>
<br>
<table class="alert-summary"> <tbody> <tr>  <td>
# Summary
</td>  </tr>  <tr>  <td>
[insert summary here]
</td>  </tr> </tbody> </table>
```

And this is the box as it renders in Rmarkdown/hugo/html:

<table class="alert-readings"> <tbody> <tr>  <td>
# Readings
</td>  </tr>  <tr>  <td>
[insert readings here]
</td>  </tr> </tbody> </table>
<br>
<table class="alert-summary"> <tbody> <tr>  <td>
# Summary
</td>  </tr>  <tr>  <td>
[insert summary here]
</td>  </tr> </tbody> </table>


## Parts of a box

All boxes have only two rows. 

The first row is dark and is currently the sand colour from Macquarie University.

The second row is 80% transparent (by putting 20 at the end of the hexidecimal color number - for 20%). 

The first row should contain one h1 heading (indicated by starting the line with a hash #).

The second row can contain h2, h3, normal text, latex/mathjax, and pretty much any other text. 

## Choosing the icon

You choose the icon for your box by indicating the name of the class in the first table tag: `<table class= "....">`.

There are eight icons to choose from:

|icon|class name|
| ---- | ----- | 
|eye-glasses|alert-readings|
|clound|alert-concepts| 
|clipboard|alert-summary|  
|toolbox|alert-box|  
|tick-box|alert-review|  
|bar-bell/weights|alert-exercises|  
|light-globe|alert-solutions|  
|test-tube|alert-exam|   

## Examples of Headings and Icons

<table class="alert-readings"> <tbody> <tr>  <td>
# Example 'alert-readings' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-concepts"> <tbody> <tr>  <td>
# Example 'alert-concepts' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-summary"> <tbody> <tr>  <td>
# Example 'alert-summary' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-box"> <tbody> <tr>  <td>
# Example 'alert-box' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-review"> <tbody> <tr>  <td>
# Example 'alert-review' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-exercise"> <tbody> <tr>  <td>
# Example 'alert-exercise' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-solution"> <tbody> <tr>  <td>
# Example 'alert-solution' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-exam"> <tbody> <tr>  <td>
# Example 'alert-exam' Box - Heading and Icon
</td>  </tr> </tbody> </table>


# Complications

* You need a line break character between consecutive boxes
* the 'alert-box' box is the same as the others, except that the heading is in 14 font. This is so it can fit longer headings, such as those you might find on a table or figure or box in a academic paper. 

# Rationale behind the choice of this solution to the 'box problem', including a summary of tghe problems I faced while constructing the code for these boxes

The main problems I had to solve were:

1. How to make 'alert' shortcodes work in Hugo/academic theme (you can, but see point 2)
2. How to make Latex/Mathjax work inside a 'shortcode' (you can't).
3. How to make a heading from inside a 'shortcode' display in the Hugo Table of Contents (you can't).
4. How to use `<div>` tags to give a similar effect as 'shortcode' - You can do this, but the problem is that it doesn't show up in the Hugo Table of Contents for the page (so, basically you can't use it if you want TOC).
5. How to make the same materials with HTML tables.
6. How to turn off change colour on hover for HTML tables. 
7. And also just a range of generic skills such as:
    * How to use CSS
    * How does Mathjax work
    * How do classes work in CSS
    * How to call multiple classes on the one set of text (it is possible, you just put the classes as separate words inside the same set of double inverted commas in CSS).
    * What the boxes look like when I make eight different colours based on the eight colours of MQ logos (it doesn't work - just one looks better).
    * How to make a color transparent, such as #a34b2b20.
    * How to find and load logos into a webpage through CSS
8. How to change the distance between headings and the top and bottom of boxes, and also how to lift boxes closer to text when you end with a list, or start with a heading.
9. How to keep all of this as close as possible to the intentions of Markdown - which are supposed to be clean, simply layed out documents - not full of HTML and other code. 
10. The distinction between the three verisons of the files on my computer:
	* the Rmd
	* the first round of HTML generated by rmarkdown and stored with the Rmd file.
	* the second round of HTML files, which are all called index.html, and which have been processed by Hugo.

# Solutions

Remember:

1. spell alert correctly (it is not alter)
2. don't start a table again half way through making the table by including `<table>` or `<tbody>` tags.
3. Include a `<br>` between consecutive boxes.

# Future developments

It might be possible to build this within a markdown table, and preserve more markdown, and use less HTML tags. 

For example, the following code

```
| <i class="fas fa-cloud"></i> Summary |
| ------ |
| [insert text here] |

```

produces this table:

| <i class="fas fa-cloud"></i> Summary |
| ------ |
| [insert text here] |

**However**, there are multiple problems:

1. I can't get markdown headings (e.g. # for h1) to work wihthin a markdown table
2. Without headings it won't index
3. I don't think the second row of the markdown table would handle a large amount of text, including latex, if we wanted to do a inset box with latex equations in it. 

An alternative might be to just create a generic 'box' HTML table, and then put whatever icon I want within that. **However,** this would also have problems, such as:

1. It would still need the same code as for the current alert tables (i.e. the four tags to start it, and the class specification).
2. It would require additional specification of the icon (e.g. a line like `<i class="fas fa-cloud"></i>`.
3. I don't think the `<i>` could be placed in the markdown and still get the effect we are looking for. This is because the h1 is specified with a #, which I think needs to be at the beginning of the line, and after an empty line. So we are then back to the css where we specify h1:before ... for the icon. 
4. So it probably wouldn't work, and we have the best we can do at the moment. 

For example, look how this renders. 

The first table is our current set up. The second table inserts an <i> icon  before the h1 #, but it breaks the style sheet AND the markdown:

```
<table class="alert-exam"> <tbody> <tr>  <td>
# Example 'alert-exam' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-exam"> <tbody> <tr>  <td>
	<i class="fas fa-cloud"></i>
# Example 'alert-exam' Box - Heading and Icon
</td>  </tr> </tbody> </table>
```

<table class="alert-exam"> <tbody> <tr>  <td>
# Example 'alert-exam' Box - Heading and Icon
</td>  </tr> </tbody> </table>
<br>
<table class="alert-exam"> <tbody> <tr>  <td>
<i class="fas fa-cloud"></i>
# Example 'alert-exam' Box - Heading and Icon 
</td>  </tr> </tbody> </table>


# Solution with grid_tables (a type of pandoc markdown table?

See section "Customised Boxes (Gridtables)"