---
title: "Markdown Syntax and Styling"

lastmod: 2019-03-06T00:00:00.000Z

draft: false
type: docs
maths: true	

output:
  blogdown::html_page:
    toc: true

linktitle: "Markdown Syntax and Styling"
menu: 
  docs:
    parent: Content Management
    weight: 80

---
 
## Escaping RMarkdown

Sometimes there are situations in which you want to escape the RMarkdown syntax. For example, if you want to have \*text with asterisks\* and not have it be in itallics like *this*. To do this use a backslash (\\) behind each character with special meaning. 

An example is:

\\\* text \\\*

which will render like:

\*text\*

## Headings

Headings are rendered by using a # before the heading content. There are six heading levels which are triggered using more #. So a level four heading would be done like this:

\#### Heading

Which would appear like this:

#### Heading

Note: The table of contents for the Methods101 site will only pick up on heading levels 1 through 3 when generating.

## Formatting content

For a Markdown cheat sheet go [here.](https://www.markdownguide.org/cheat-sheet/) 

Some useful RMarkdown formatting commands (these are the same as Markdown):

**Bold text:** Use a double ** before and after the text like this \**bold text\** which will render like this **bold text**

**Itallic text:** Use a single * before and after the text like this \*itallic text\* which will render like this *itallic text*

Lists are either ordered or unordered. 

**Unordered lists** are created like this:

\* List

\* List

\* List

And render like this:

* List

* List

* List

**Ordered lists** are created (and rendered) like this:

1. List

2. List

3. List

If you would like to indent the text like this:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Indented text

Then use \&nbsp; for each space you would like the text to be indented by (the above was six spaces). This can also be done using HTML.

## Formatting with HTML

RMarkdown cannot style the text. Instead, to style the text you need to insert HTML into the RMD document. 

To colour the text use the following:

\<span style=color:maroon> Coloured text \</span>  

Which will render like this:

<span style=color:maroon> Coloured text </span> 

Some available colours can be found [here](https://www.w3schools.com/colors/colors_names.asp) .

Instead of colour any of the numerous CSS styling options can be inserted. More options can be found [here](https://www.w3schools.com/css/css_text.asp) and elsewhere with a quick google search.

## Dollar signs in text

Problem:

* "How do you insert a dollar sign into text, such as US<span>&#36;</span>50?"
* The escape characters were not working. Neither ```\$``` or ```\\$``` worked. 
* The cause was some interaction between the layers of processing of the text file - so the dollar sign would get created in one layer of processing, and then interpreted as maths for the next. 

Solution: 

* ```<span>&#36;</span>```

So for example, this text renders correctly: 

Code: 

``` 
"How do you insert a dollar sign into text, such as US<span>&#36;</span>50?" 
```


Renders as: 

"How do you insert a dollar sign into text, such as US<span>&#36;</span>50?"




## Symbols in text - use HTML

We need to use HTML symbols (between <span> tags) for most symbols.

This is a useful website where you can easily look up HTML tags for symbols

https://www.rapidtables.com/web/html/html-codes.html

## Adding borders to images

The following text adds borders to images, if included after the YAML in each page.

```
<style> img { padding:1px; border:1px solid #021a40; } </style>
```

## Formulas with Latex Maths
Latex Maths is the best way to render formulas. 

You use a single dollar sign <span>&#36;</span> for inline formulas, and a double dollar sign <span>&#36;</span><span>&#36;</span> for formulas that appear in the middle of the page on their own line. 

I (Nick) have found that it is better to use the single dollar signs, and the formula listed below, as it allows you to layout the formulas and the definitions of terms in a more tight and neat manner.

Note that the & sign indicated the part of each line that should be aligned with the others.
Also ```\text``` is a useful command, as it allows you to put text and spaces into the lines of Latex maths.

The double backslash ```\\``` means end of line.

```
$\begin{aligned}
r = &\frac{\sum_{i=1}^n (x_i - \bar x)(y_i - \bar y)}{(N-1)s_x s_y} \\
\\
\text{Where:} \\
\bar x = &\text{ mean of x} \\
\bar y = &\text{ mean of y} \\
\bar N = &\text{ number of observations} \\
s_x = &\text{ standard deviation of x} \\
s_y = &\text{ standard deviation of y} \\
\end{aligned}$

$\begin{aligned}
y = &b_1 x_1 + b_2 x_2 + b_3 x_3 + ... + b_0 + e \\
\\
\text{Where:} \\
y=&\text{ dependent variable (outcome variables)} \\
x_1 , x_2 , \text{ ... }x_n = &\text{ independent variables (predictor variables)} \\
b_1 , b_2 , \text{ ... }b_n  = &\text{ slope of relationship between }y\text{ and }x_1 , x_2 , \text{ ... }x_n  \\
b_0 = &\text{ intercept (i.e. value of }y \text{ when all }x=0 \text{)} \\
\end{aligned}$
```


$\begin{aligned}
r = &\frac{\sum_{i=1}^n (x_i - \bar x)(y_i - \bar y)}{(N-1)s_x s_y} \\
\\
\text{Where:} \\
\bar x = &\text{ mean of x} \\
\bar y = &\text{ mean of y} \\
\bar N = &\text{ number of observations} \\
s_x = &\text{ standard deviation of x} \\
s_y = &\text{ standard deviation of y} \\
\end{aligned}$

$\begin{aligned}
y = &b_1 x_1 + b_2 x_2 + b_3 x_3 + ... + b_0 + e \\
\\
\text{Where:} \\
y=&\text{ dependent variable (outcome variables)} \\
x_1 , x_2 , \text{ ... }x_n = &\text{ independent variables (predictor variables)} \\
b_1 , b_2 , \text{ ... }b_n  = &\text{ slope of relationship between }y\text{ and }x_1 , x_2 , \text{ ... }x_n  \\
b_0 = &\text{ intercept (i.e. value of }y \text{ when all }x=0 \text{)} \\
\end{aligned}$

