---
title: "Setting Up A Site From Scatch"

lastmod: 2019-03-06T00:00:00.000Z

draft: false
type: docs
maths: true	

linktitle: "Setup From Scratch"
menu:
  docs:
    parent: Website Management
    weight: 40

---


# Summary


# Step 1: Create a Gmail

You want to sent up a brand new gmail account for two reasons:

1. It will mean you will have a Gmail, Github, and Netlify accounts for your organisation and the website which you can share and transfer with other members of the organisation (or collaborators) without compromising your own personal gmail/github/netlify account.
2. Netlify has a limit of one free netlify hosting per Github account.

Go to www.gmail.com and create a new email address.

You will need a mobile phone number to send an SMS to for verification of your identity.

If you are looking for ideas for passwords, check out this XKCD comic.

https://xkcd.com/936/

And this automatic password generator

https://preshing.com/20110811/xkcd-password-generator/

# Create a Github account

Now go to www.github.com and set up a normal free Github account.

# Clone the methods101 template (or whatever)

BEFORE creating a new repository, follow these steps

When logged into your Github account:

1. Click on the plus sign (+) in the top right hand corner of the github screen
2. Select "Import repository"
3. On the next page there are two boxes you need to fill out.
	* Under the 2nd set of boxes "Your new repository details", insert the name of your repository in the box below "Name"
	* In the 1st box "Your old repository's clone URL", you will need to get the clone URL from your old repository (e.g. methods101.com) by following the steps in these instructions: https://help.github.com/en/articles/cloning-a-repository


# Create Netlify account

Go to Netlify and log in with your Github account.

1. On the main page of your account, in the "Sites" tab, click "New site from Git" button in the top right corner.
2. On the next page called "Create a new site", under "Continuous Deployment", click "Github"
3. You will be asked to authorise Netlify to access your account, so click the green button "Authorise Netlify by Netlify"
4. Change the next page first button selection to "Only select repositories", and then in the pull down menu select the repository you want to launch/host. And then click "Install".
5. It should then go to the the third stage of setting up called "2. Build options and deploy!" [NOTE: We had trouble here, but just reloaded the pages, and then clicked on "New site from Git" and then went straight to "3. Build options, and deploy"] Default settings here should be fine: 

	* you are the owner, 
	* branch is master, 
	* build command is hugo,
	* public director is public.  

Click "Deploy site."
6. It will now show "Site deploy in progress". Click on "General", and under "Site details" and "Site information", click the button "Change site name" =, and change the name to some name you want (e.g. sydnet, so now the basic domain name deployed by netlify is hosted at: sydnet.netlify.com )


# Change the default page to /doc/

# buy a website and link to netlify



